name: projeto_integrador_6
description: A Flutter app to simplify shopping, using the camera to scan receipts, track inventory, and create personalized lists.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

dependency_overrides:
  path: ^1.9.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.1.5
  path: ^1.9.1
  image: ^4.3.0
  mongo_dart: ^0.10.3
  google_mlkit_text_recognition: ^0.14.0
  flutter_bcrypt: ^1.0.8
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  cunning_document_scanner: ^1.2.3
  shared_preferences: ^2.3.3
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  syncfusion_flutter_pdf: 27.1.58
  string_similarity: ^2.1.1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/icons/

  fonts:
    - family: Space Grotesk
      fonts:
        - asset: fonts/space-grotesk/SpaceGrotesk-VariableFont_wght.ttf